### ISSUE TITLE
document diffing

### ISSUE THREAD

**Issue by sonnyp** [chbrown/rfc6902#11]
https://github.com/chbrown/rfc6902#determinism

> which might explain why there are more than five patch-applying RFC6902 implementations in NPM, but only one (this one) that attempts to generate patch documents from two distinct objects

Actually no, https://github.com/JSON8/patch#diff (I'm the author).
But this was most likely implemented after you wrote that.

**Comment by chbrown** [comment]
Indeed, JSON8/patch@45c9b5f133e7ce15627bf43427b24def1b18218f (Jul 15, 2015) was temporally preceded by chbrown/rfc6902@1235375230c3c2cc9b367042a44b14df0804c115 (Jan 23, 2014).

`git blame` isn't useful just for blaming, but for historical inquiry too! 😄 

You're also right that it's no longer true. I'll use a more accurate / future-proof wording.
