### ISSUE TITLE
Object key order

### ISSUE THREAD

**Issue by kellyselden** [chbrown/rfc6902#22]
Would you accept a PR that was additive of the spec, but still compliant, that preserved key order (best attempt)? This is very useful if you are processing an npm "package.json" and want a nice looking git diff when you save to disk. I have it working in a project of mine, but would love to merge it upstream. It doesn't modify patch structure, it just has a third argument to `applyPatch` that is the same object that you used as the `output` in `createPatch`. It uses the object to detect the ordering needed. Here is a sample of how I'm using it now:

```js
let patch = rfc6902.createPatch(source, theirs);

// this only handles the subset of the patch that requires adding ordered object keys
let remainingPatch = applyPatch(ours, patch, theirs);

rfc6902.applyPatch(ours, remainingPatch);
```

Implementation: https://github.com/kellyselden/ember-cli-update/blob/package-json/src/apply-patch.js
Tests: https://github.com/kellyselden/ember-cli-update/blob/package-json/test/unit/apply-patch-test.js

Your API could add an optional third arg to `applyPatch` that, if supplied, used it to apply object key ordering.

cc @rwjblue

**Comment by chbrown** [comment]
I kinda like the idea of having key-order-cognizant diffing somewhere in this library, but I don't think that `applyPatch` is the place for it. `applyPatch` can also be applied to an Array, in which case the third argument doesn't make much sense.

In my experience with JS, object key ordering is a bit finicky and not something you'd generally want to rely on, but I can see how it would be handy to control when the result will be linearly interpreted, as in a git diff.

If you wanted to create a RFC6902 patch to fix object ordering, it'd basically work like your implementation does, dropping everything that's not in the right place, and then adding it back. Which doesn't seem particularly efficient or elegant.

The more I think about it, though, the more I think the best solution for what you appear to be doing is to use the `rfc6902.createPatch` and `rfc6902.applyPatch` methods as-is, then run the result through some new `matchObjectKeyOrdering(ours, theirs)` function, like your function at https://github.com/kellyselden/ember-cli-update/blob/cc63716/src/apply-patch.js#L3-L28

If I'm misunderstanding your use-case, please elaborate on what you're trying to do.

I'd consider a PR that implements a diff function between two objects, `source` and `target`, that returns a RFC6902 patch that manipulates the `source` object to have the key-ordering in `target`, but that seems bulky, and not really what RFC 6902 was designed for.

But I don't think `applyPatch` is the right place for the special case you're describing.
