### ISSUE TITLE
How about return the old values if it exists?

### ISSUE THREAD

**Issue by lichenhao** [chbrown/rfc6902#26]
If the old values can be send back with any actions, so it will be able to go back.
But now, the each action return null as default. So it would never go back.

**Comment by chbrown** [comment]
I cannot tell from your question what you're trying to do.

Please can you provide a minimal example comparing current behavior with desired results?

**Comment by lichenhao** [comment]
For example:

```
import {applyPatch} from 'rfc6902'
const target = []

const opAdd = {op: 'add', 'path': '/-', value: {name: 'init'}}
const resetOp = applyPatch(target, opAdd) // now the target is `[{name: 'init'}]`

// if resetOp is `{op: 'del', 'path': '/0'}`, the target object can be reset by it

// try to send back
applyPatch(target, resetOp)
// now the target is back to `[]`
```
So if this can return the detail for each action, all of it can be back

**Comment by gabe0x02** [comment]
He wants an undo.

**Comment by chbrown** [comment]
Ok, I think I see what you want.

It could be cool to create an `function undoPatch(op: Operation): Operation`, but I expect it might be trickier to cover all the edges cases than seems immediately apparent.

You could accompany it with a `function applyPatchWithUndos(object, patch: Operation[]): Operation[]` that would then call `applyPatch(object, patch)` and `patch.map(undoPatch)` under the hood, but again, order of operations might be tricky to reverse into a functional "undo-all" patch.

I'd welcome a PR, with tests, but I don't anticipate implementing such a feature myself at this time.

(Thanks, @gabe0x02, for the elucidation; I was still puzzling over that last comment until I saw yours.)

**Comment by gabe0x02** [comment]
If OP wants to go back they can always just use the diff functionality.
