### ISSUE TITLE
createPatch wrong when switching array elements

### ISSUE THREAD

**Issue by LennartC** [chbrown/rfc6902#4]
var patches = rfc6902.createPatch([ "A", "B" ], [ "B", "A" ]); // produces:
    {"op":"add","path":"/0","value":"B"}	Patch 0
    {"op":"remove","path":"/1"}	Patch 1

And this is wrong. The first patch makes the array look like:
   
     [ "B", "A", "B" ]

And because the patches are sequential, the second patch will remove A, making it look like
    
    [ "B", "B" ]

So the second patch should be:
    
    {"op":"remove","path":"/2"}

**Comment by dhritzkiv** [comment]
Looks like this could be related to #3 (my issue), as it relates to arrays, and doesn't necessarily produce a patch that results in the desired outcome.

**Comment by LennartC** [comment]
You are correct, it's the same issue as #3 . And where you say:

    /*
    `diff` is equal to:
     [ 
        { op: 'remove', path: '/arr/1' },
        { op: 'remove', path: '/arr/2' }
     ]
    which is correct
    */

It is actually wrong. It should be:

     [ 
        { op: 'remove', path: '/arr/1' },
        { op: 'remove', path: '/arr/1' }
     ]

**Comment by dhritzkiv** [comment]
@LennartC Good catch! I'll update my issue.

**Comment by chbrown** [comment]
Thanks for the bug report. Fixed in v1.0.5. See my comment in #3 for explanation.
