### ISSUE TITLE
Version 3 does not work on objects without hasOwnProperty function

### ISSUE THREAD

**Issue by mjdickinson** [chbrown/rfc6902#41]
It is possible for a JS object not to inherit from Object.prototype and hence not have a hasOwnProperty function.  See [here](https://stackoverflow.com/questions/15518328/creating-js-object-with-object-createnull).

The objects resulting from a GraphQL query do not inherit from Object.prototype.  See [here](https://github.com/graphql/express-graphql/issues/177).

The fix is to use `Object.prototype.hasOwnProperty.call(p, someKey)` instead of `p.hasOwnProperty(someKey)`.

**Comment by chbrown** [comment]
Fixed by #42
