### ISSUE TITLE
Operation order for arrays fields is reversed when creating patches

### ISSUE THREAD

**Issue by dhritzkiv** [chbrown/rfc6902#5]
Seems that operations for arrays are created in the reverse order. [Here's a Gist](http://requirebin.com/?gist=da9a5fd6b17c7d41aba5)

This is probably a result of the fix that fix the order of operations when removing elements.

Solution might be as simple as calling a `.reverse()` or similar

**Comment by chbrown** [comment]
Arrgh! :) Okay, good example, I think I'll have to compose operations differently depending on whether they are insertions or deletions. Substitutions are easy.

**Comment by chbrown** [comment]
Okay, I removed my `operations.reverse()` hack and track indices properly now as of `v1.0.6`. So the operations you get back from `diffArrays()` make more sense, since they are in ascending order... plus, they work. Or they should! Keep up the good bug-testing.

**Comment by dhritzkiv** [comment]
Confirming that it works well. Thanks!

**Comment by chbrown** [comment]
PS. I edited the OP to add the gist contents, which at first didn't load at all, then was super slow.
