### ISSUE TITLE
Consider exposing ES6 modules

### ISSUE THREAD

**Issue by chrisvariety** [chbrown/rfc6902#6]
First off, rfc6902 looks great, so thanks :sparkles: 

I'm getting this error when using this library with [webpack](http://webpack.github.io/):

> WARNING in ./~/rfc6902/rfc6902.js
> Critical dependencies:
> 1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
>  @ ./~/rfc6902/rfc6902.js 1:480-487

Unfortunately the original source files aren't available in the package distributed via npm due to your [.npmignore](https://github.com/chbrown/rfc6902/blob/master/.npmignore). 

Can you consider un-excluding the source JS files for us folks that can speak ES6 and prefer to consume ES6 when available?

Thanks!

**Comment by chbrown** [comment]
Good idea. Fixed as of fe0f762 / v1.0.7

(I'm just starting to experiment with webpack on other projects, but I'm not sure migrating from browserify to webpack for this project would benefit anything; if you have any suggestions for a better build process let me know.)

**Comment by chrisvariety** [comment]
Thanks so much! Just one little thing... with `index.js` still ignored, it seems like I would have to re-implement `createPatch` and `applyPatch` on my end. I could totally just be missing something though--

On another note, I don't see any benefit moving this particular project to webpack -- most of the fanciness would be lost as it's a pretty tight little package without any external dependencies.

**Comment by chbrown** [comment]
Haha, stupid Saturday morning me. `index.js` is now also un-ignored as of `v1.0.8`.

**Comment by chrisvariety** [comment]
Thanks! Working great now! :sparkles:
