### ISSUE TITLE
Error : Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by rutvik18** [chbrown/rfc6902#8]
My Doc : 

`{ name: {},
  display_picture: {},
  address: [],
  contact: { emails: [], phones: [] },
  urls: {},
  referral_id: {},
  agency_meta: {},
  aggrements: {},
  languages: [ { ability: [Object], name: 'English' } ],
  work_exp: [],
  dreams: [],
  idols: [],
  interests: [],
  events: [],
  created_at: Fri Feb 19 2016 05:08:20 GMT+0000 (UTC),
  updated_at: Fri Feb 19 2016 05:08:20 GMT+0000 (UTC),
  is_active: 1,
  user_id: 'S34DDF',
  profile_type: 'talent',
  display_name: 'Bhumin Patel',
  profile_id: 1,
  _id: 56c6a01d83f7d45b84f37357 }`

Given other doc  that is changed : 
`{ display_name: 'Rutvik' }`

Patches Generated: 
`[ { op: 'remove', path: '/$__' },
  { op: 'remove', path: '/isNew' },
  { op: 'remove', path: '/errors' },
  { op: 'remove', path: '/_doc' },
  { op: 'remove', path: '/$__original_save' },
  { op: 'remove', path: '/save' },
  { op: 'remove', path: '/_pres' },
  { op: 'remove', path: '/_posts' },
  { op: 'remove', path: '/db' },
  { op: 'remove', path: '/discriminators' },
  { op: 'remove', path: '/__v' },
  { op: 'remove', path: '/id' },
  { op: 'remove', path: '/_id' },
  { op: 'remove', path: '/last_modified_date' },
  { op: 'remove', path: '/is_active' },
  { op: 'remove', path: '/updated_at' },
  { op: 'remove', path: '/created_at' },
  { op: 'remove', path: '/events' },
  { op: 'remove', path: '/interests' },
  { op: 'remove', path: '/idols' },
  { op: 'remove', path: '/dreams' },
  { op: 'remove', path: '/work_exp' },
  { op: 'remove', path: '/languages' },
  { op: 'remove', path: '/aggrements' },
  { op: 'remove', path: '/agency_meta' },
  { op: 'remove', path: '/is_agency' },
  { op: 'remove', path: '/referral_id' },
  { op: 'remove', path: '/current_step' },
  { op: 'remove', path: '/urls' },
  { op: 'remove', path: '/contact' },
  { op: 'remove', path: '/address' },
  { op: 'remove', path: '/birthdate' },
  { op: 'remove', path: '/gender' },
  { op: 'remove', path: '/about' },
  { op: 'remove', path: '/tagline' },
  { op: 'remove', path: '/display_picture' },
  { op: 'remove', path: '/name' },
  { op: 'remove', path: '/profile_type' },
  { op: 'remove', path: '/user_id' },
  { op: 'remove', path: '/profile_id' },
  { op: 'remove', path: '/schema' },
  { op: 'remove', path: '/collection' },
  { op: 'remove', path: '/$__handleSave' },
  { op: 'remove', path: '/$__save' },
  { op: 'remove', path: '/$__delta' },
  { op: 'remove', path: '/$__version' },
  { op: 'remove', path: '/increment' },
  { op: 'remove', path: '/$__where' },
  { op: 'remove', path: '/remove' },
  { op: 'remove', path: '/model' },
  { op: 'remove', path: '/on' },
  { op: 'remove', path: '/once' },
  { op: 'remove', path: '/emit' },
  { op: 'remove', path: '/listeners' },
  { op: 'remove', path: '/removeListener' },
  { op: 'remove', path: '/setMaxListeners' },
  { op: 'remove', path: '/removeAllListeners' },
  { op: 'remove', path: '/addListener' },
  { op: 'remove', path: '/$__buildDoc' },
  { op: 'remove', path: '/init' },
  { op: 'remove', path: '/$__storeShard' },
  { op: 'remove', path: '/hook' },
  { op: 'remove', path: '/pre' },
  { op: 'remove', path: '/post' },
  { op: 'remove', path: '/removePre' },
  { op: 'remove', path: '/removePost' },
  { op: 'remove', path: '/_lazySetupHooks' },
  { op: 'remove', path: '/update' },
  { op: 'remove', path: '/set' },
  { op: 'remove', path: '/$__shouldModify' },
  { op: 'remove', path: '/$__set' },
  { op: 'remove', path: '/getValue' },
  { op: 'remove', path: '/setValue' },
  { op: 'remove', path: '/get' },
  { op: 'remove', path: '/$__path' },
  { op: 'remove', path: '/markModified' },
  { op: 'remove', path: '/modifiedPaths' },
  { op: 'remove', path: '/isModified' },
  { op: 'remove', path: '/$isDefault' },
  { op: 'remove', path: '/isDirectModified' },
  { op: 'remove', path: '/isInit' },
  { op: 'remove', path: '/isSelected' },
  { op: 'remove', path: '/validate' },
  { op: 'remove', path: '/$__validate' },
  { op: 'remove', path: '/validateSync' },
  { op: 'remove', path: '/invalidate' },
  { op: 'remove', path: '/$markValid' },
  { op: 'remove', path: '/$isValid' },
  { op: 'remove', path: '/$__reset' },
  { op: 'remove', path: '/$__dirty' },
  { op: 'remove', path: '/$__setSchema' },
  { op: 'remove', path: '/$__getArrayPathsToValidate' },
  { op: 'remove', path: '/$__getAllSubdocs' },
  { op: 'remove', path: '/$__registerHooksFromSchema' },
  { op: 'remove', path: '/$__handleReject' },
  { op: 'remove', path: '/$toObject' },
  { op: 'remove', path: '/toObject' },
  { op: 'remove', path: '/toJSON' },
  { op: 'remove', path: '/inspect' },
  { op: 'remove', path: '/toString' },
  { op: 'remove', path: '/equals' },
  { op: 'remove', path: '/populate' },
  { op: 'remove', path: '/execPopulate' },
  { op: 'remove', path: '/populated' },
  { op: 'remove', path: '/depopulate' },
  { op: 'remove', path: '/$__fullPath' },
  { op: 'replace', path: '/display_name', value: 'Rutvik' } ]`

Why all this operations are generated ? I just want the last one replace op? Plus why unknown paths are showing in generated patch ( { op: 'remove', path: '/toObject' }) ? Is that a reason to cause above mentioned error?

**Comment by chbrown** [comment]
Your first object (Bhumin Patel) is a dirty Angular-enhanced object, and the second one (Rutvik) is not.

`rfc6902` uses `for (var key in obj) { ... }` to determine the valid keys on an object, so it's going to pick up _all_ the properties in your object. That's something that might need re-evaluation, but for now if you use a POJO (plain old javascript object) on each side, you'll avoid a lot of that garbage.

IIRC, you can use `var cleanCopy = angular.copy($scope.whatever)` and then say `rfc6902.createPatch(cleanCopy, myRutvikObject)` instead of `rfc6902.createPatch($scope.whatever, myRutvikObject)`, which will give you better output.

You'll still get patches like `{ op: 'remove', path: '/idols' }`, but that's because Mr. Rutvik legimately doesn't have an `idols` key.

**Comment by rutvik18** [comment]
Hey,
Thanks for a quick turnaround.

The first document (Bhumin Patel), is something I received as a query result from Mongoose using node. I can access its properties like a Pojo. Not sure if the scope is added by Mongoose. Is that so?

**Comment by chbrown** [comment]
Oh god, Mongoose is even worse than Angular. Sorry, I was jumping to conclusions there — all the dollar signs immediately made me think of Angular. I think with Mongoose you have to call `.toObject()` or `.toJSON()` or something on your result.

I'm so, so sorry for you. MongoDB happens. But it gets better.
