### ISSUE TITLE
[question] test runner

### ISSUE THREAD

**Issue by ddimitrioglo** [chbrown/rfc6902#80]
As you mentioned before you do care about the dependencies you chose for the project, wanted to ask you if why you have chosen `ava` as a test runner vs many others?

IMHO, mocha is better known on the market and has a way smaller dependencies tree:
1. ava
![image](https://user-images.githubusercontent.com/9005667/111023116-d76b2100-83df-11eb-8fe0-c0df239769c2.png)

2. mocha
![image](https://user-images.githubusercontent.com/9005667/111023138-f7024980-83df-11eb-9643-8fa26b68faee.png)

**Comment by chbrown** [comment]
`devDependencies` are a totally different ballgame.

If you look back through the history you'll see I used to use mocha.

This is not a good issue, and it's starting to feel like you're trolling. Please stop.

**Comment by ddimitrioglo** [comment]
that was just a question... unfortunately there is no other way to communicate with the repo owner... sorry about that, won't happen again
